модуль  и модуль 3
js-tasks-ru/jsbasic-20200727_aleksey-sokolov pull request #3
Opened 2020-08-09 17:36 UTC by sokolik1983-hub

2020-08-09 17:43 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Фильтрация по диапазону
+ должна фильтровать диапазон
+ не должна менять исходный массив
```
```diff
Найти min/max в строке
+ 25,-1,-234,4,   1000
+ 1, -5.8 или 10, хотя 34 + -5.3 и 73
```
```diff
Функция showSalary(users, age)
+ для пользователей до 30 лет должна вывести строку с зарплатами
+ для пользователей до 40 лет должна вывести строку с зарплатами
```
```diff
Переведите текст вида border-left-width в borderLeftWidth
+ должна преобразовать '-webkit-transition'
+ должна преобразовать 'background-color'
+ должна оставить пустую строку без изменений 
+ должна преобразовать 'list-style-image' 
```
```diff
Трансформировать в массив имён
+ должна преобразовать users в массив имён
```
```diff
Создайте калькулятор
+ должно умножать числа
+ должно складывать числа
```
```diff
Определите, пуст ли объект
+ объект со свойством undefined должен считаться не пустым
+ объект с удалённым свойством - пустой
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
```
```diff
Функция sumSalary(salaries)
+ должна игнорировать свойства других типов
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-08-10 09:16 UTC, dolgachio requested changes

2020-08-10 09:16 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +  delete salaries["isPayed"];
Зачем здесь эта строчка? Удалять из исходного объекта, ничего не нужно, удалите ее, пожалуйста

2020-08-10 09:16 UTC, stas-dolgachov commented on 2-module/2-task/index.js
> +  if (Object.keys(obj).length > 0) {
👍

2020-08-10 09:16 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  calculator.sum = function () {
При такой записи, при каждом новом `read` будет присваивать новую функцию `sum`. Правильней будет ее присваивать по аналогии с `mul`. Сделайте, пожалуйста, похожим образом.

2020-08-10 09:16 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  return (calculator.stNum+calculator.ndNum);
Здесь лучше использовать `this` вместе переменной `calculator`.

2020-08-10 09:16 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  return (calculator.stNum*calculator.ndNum);
Здесь лучше использовать `this` вместе переменной `calculator`.

2020-08-10 09:16 UTC, stas-dolgachov commented on 3-module/1-task/index.js
> +  let usersName = [];
В качестве альтернативы, эту задачу можно решить с помощью метода `map`.

2020-08-10 09:16 UTC, stas-dolgachov commented on 3-module/2-task/index.js
> +  let newMassive = [];
В качестве альтернативы, эту задачу можно решить с помощью методов `map` и `filter`.

2020-08-10 09:16 UTC, stas-dolgachov commented on 3-module/4-task/index.js
> +    let result = (keys.name + ", " + keys.balance + '\n');
`\n` вы можете добавить в самом конце, когда делает `join('\n')`. Это позволит избавиться от манипуляций с удалением самого последнего символа переноса строки.

2020-08-10 09:16 UTC, stas-dolgachov commented on 3-module/5-task/index.js
> +  let result = {};
👍

2020-08-11 14:49 UTC, jsru commented
@stas-dolgachov ping :)

2020-08-11 18:23 UTC, dolgachio approved these changes
Спасибо, что внесли изменения!

2020-08-11 18:23 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +    this.sum = function () {
Определение методов `mul` и `sum` я все-таки рекомендую вынести из метода `read`.
Понятно зачем это делать? 

Я немного неправильно изначально написал, определение обоих методов желательно вынести из `read`.

2020-08-11 18:23 UTC, merged